### ISSUE TITLE
[PE-D][Tester D] Deadline before today is acceptable

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-2/tp#190]
![image.png](https://raw.githubusercontent.com/nixonwidjaja/ped/main/files/9719e687-d074-471e-8928-feb1b48a4dcb.png)

Based on the user guide, I thought the app is supposed to help manage internship application. But when I tried to add internship with passed deadline, it still accepts my entry without any warning whatsoever.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: nixonwidjaja/ped#3

**Comment by papataco14** [comment]
This is an intended feature, as the user might want to add entries for record keeping purposes. As the developers, we do not want to restrict the manners in which users might want to use the application with overzealous input validation. Closed as its not a feature flaw.
