### ISSUE TITLE
[PE-D][Tester A] [UG] Broken link in Quick Start section

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-2/tp#194]
The "click here" link seems to be broken. It did not lead me to anywhere.

![image.png](https://raw.githubusercontent.com/HugeNoob/ped/main/files/45b8a865-555e-44be-9901-12837461e627.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: HugeNoob/ped#2

**Comment by papataco14** [comment]
Fixed in #226
