### ISSUE TITLE
[PE-D][Tester E] Incorrect formatting in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-2/tp#197]
In the remark section, the points under more examples are not correctly formatted
![Screenshot 2023-11-03 162411.png](https://raw.githubusercontent.com/wjayee/ped/main/files/c1beea41-d42e-4019-ae7d-7b2b319c09bc.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: wjayee/ped#1

**Comment by papataco14** [comment]
Closed due to duplication with #214
