### ISSUE TITLE
[PE-D][Tester A] [UG] Broken link in Quick Tour section

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T17-2/tp#200]
This link does not seem to lead me anywhere. I noticed this issue in other similar boxes below too.

![image.png](https://raw.githubusercontent.com/HugeNoob/ped/main/files/b258b4e8-4f53-4360-a332-b928cd93311b.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: HugeNoob/ped#5

**Comment by papataco14** [comment]
Fixed in #226
