### ISSUE TITLE
[PE-D][Tester A] [UG] Mismatch between explanation and image

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-2/tp#204]
The text example is about "view 6" and "twitter", but the images are showing "view 3" and "DSTA" instead.

The examples are definitely still understandable, but the difference is a little jarring.

![image.png](https://raw.githubusercontent.com/HugeNoob/ped/main/files/cf2acb17-cfc6-4bbb-86fb-55c8bb12b78c.png)

![image.png](https://raw.githubusercontent.com/HugeNoob/ped/main/files/3829efb4-7f67-4258-a38e-70dbd137e384.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: HugeNoob/ped#6

**Comment by papataco14** [comment]
Closed due to duplication with #207
