### ISSUE TITLE
[PE-D][Tester C] Window size on startup is too small

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-2/tp#218]
<i><video controls><source src="https://raw.githubusercontent.com/kokrui/ped/main/files/51a46352-ab7d-44f9-80b6-1c64e130bfa8.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/kokrui/ped/main/files/51a46352-ab7d-44f9-80b6-1c64e130bfa8.mov</i>

When starting the jar from a fresh new directory, the window size does not show all information. In the linked video, this is evidenced by the scroll bar on the far right of the Company List Panel not being shown

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kokrui/ped#12

**Comment by papataco14** [comment]
The app is meant to be used at the maximized window size for best user experience. Will add to our UG to make this clear.
