### ISSUE TITLE
Sort command error message incorrect

### ISSUE THREAD

**Issue by papataco14** [AY2324S1-CS2103T-T17-2/tp#237]
Step 1: Type `sort afnieaanaifnwanafneanaeoenaervno`

Step 2: Observe error message below
![image](https://github.com/AY2324S1-CS2103T-T17-2/tp/assets/108869153/be5edd30-2400-4793-8daf-73885e756cc4)

It states that the command format is incorrect, which is wrong.

**Comment by AlagappanRa** [comment]
This one can fix. Wrong error message output can be fixed, he said in the forum
