### ISSUE TITLE
UG problems

### ISSUE THREAD

**Issue by papataco14** [AY2324S1-CS2103T-T17-2/tp#294]
# Format

Line(s): Problem
Before: 
> What it was

Suggestion: 
> What you suggest

---

Or anything that makes sense. [Link](https://github.com/AY2324S1-CS2103T-T17-2/tp/blob/master/docs/UserGuide.md)

One person, one comment. Edit your comments.

**Comment by papataco14** [comment]
8: Weird motto
Suggestion: _Your one-stop internship application tracker_

17-20: Test

**Comment by tayruxin** [comment]
[**line 640:**](https://github.com/AY2324S1-CS2103T-T17-2/tp/blob/617a9c7009407ed6fd58ab25d7de4e6aa9f5ebd2/docs/UserGuide.md?plain=1#L640) Phrasing abit weird 

Before:
> _You've applied to many companies, and now you want to track internship applications for a particular company. Use the `find` command to quickly locate the company you want!_

Suggestion: 
> _You've applied to many companies, and now you wish to monitor your internship applications for a specific company. Use the `find` command for a swift and efficient way to locate the company you want!_

**Comment by tayruxin** [comment]
## Listing all Contacts

**line 687:** Weird phrasing 

Before:
> Whenever LinkMeIn is started, you will see the full list of companies displayed by default (i.e. `list` command is executed automatically).

Suggestion: 
> Upon launching LinkMeIn,  you will see your full list of companies. (i.e. `list` command is executed automatically).

**Comment by tayruxin** [comment]
## Filtering Companies by Application Status: 

**line 699:** after we hyperlink to application param desc, should we also have a hyperlink at 814 to hyperlink back to filter command, I think that will improve the navigability.  

------

**line 703:** improve phrasing

Before:
> You want to prepare for the upcoming interviews you have received. 

After:
> You wish to prepare for the upcoming interviews that you have secured 

----------
**line 709:** improve phrasing 

before: 
>You can then view all the companies that you have pending interviews for from the Company List Panel.

after:

> You can then check the Company List Panel for all the companies where you have pending interviews.

**Comment by tayruxin** [comment]
## Sorting Companies by Deadlines: 

**line 736*: wrong box should be the tip box 

![image](https://github.com/AY2324S1-CS2103T-T17-2/tp/assets/106758300/7573cfc4-78bf-4fac-a95f-808baa50f3fb)

**Comment by papataco14** [comment]
Fixed in #298, #299, #301, #305
