### ISSUE TITLE
Sort Command Diagram

### ISSUE THREAD

**Issue by AlagappanRa** [AY2324S1-CS2103T-T17-2/tp#312]
![image](https://github.com/AY2324S1-CS2103T-T17-2/tp/assets/96157054/72628c53-de3b-4ba4-8356-68d8cc91e6bd)

Comparator should be destroyed right after `sortedList` is returned by the self-invocation. It is de-referenced at the time of the subsequent method calls.

**Comment by papataco14** [comment]
In the code, the comparator is derefenced after the execute method ends. So not an issue
